name: master-publish

on:
  push:
    branches: 
      - rest
      - jaegerkafka
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - name: Build and Push Latest Version
        if: endsWith(github.ref, 'jaegerkafka')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/main/docker/Dockerfile.multistage
          push: true
          tags: |
            quay.io/puzzle/quarkus-techlab-data-producer:jaegerkafka
      - name: Build and Push Latest Version
        uses: docker/build-push-action@v2
        if: endsWith(github.ref, 'rest')
        with:
          context: .
          file: src/main/docker/Dockerfile.multistage
          push: true
          tags: |
            quay.io/puzzle/quarkus-techlab-data-producer:latest
